#'''Parameters config.'''#


ext: '/home/lam4003/bin/camp_mag-qc/workflow/ext'


# --- checkm --- #

checkm2_db: '/workdir/lam4003/Databases/CheckM2_05232023/uniref100.KO.1.dmnd'

# --- cmseq --- #

minqual:    30
mincov:     10
dominant_frq_thrsh:     0.8


# --- quast --- #

min_contig_len:   100
