#'''Parameters config.'''#


# --- general --- #

ext: '/home/lam4003/bin/camp_short-read-assembly/workflow/ext'
# Choose either 'megahit', 'metaspades', or both
assembler:  'metaspades,megahit' 
# The default is 'meta' (metagenomics DNA) but one of 'rna' (RNA-Seq), 'metaviral' (viral DNA in a metagenomic context), or 'metaplasmid' (plasmid DNA in a metagenomic context) can also be selected
option:     'meta'
