#'''Parameters config.'''#

# --- Methods choice --- #
# choose the method class
all: False
scaling: False
coda: False
transformation: False
batchcorr: False

# alternativaly, specify the list
fromthelist: True
methodslist:
  -  tss
  -  tmm
  -  clr
  #-  alr
  #-  ilr
  #-  blom
  #-  npn
  #-  combat
  #-  limma
